many: Simplify messages

diff --git a/atom-me-get b/atom-me-get
--- a/atom-me-get
+++ b/atom-me-get
@@ -25,7 +25,7 @@ zparseopts -E -D -A opthash h -help v -verbose q -quiet a -no-ansi n || \
 (( ${+opthash[-a]} + ${+opthash[--no-ansi]} ))  && local OPT_NO_ANSI="-a"
 
 local name="$1" value1_var_name flag2_var_name read=0 error=0
-[[ -z "$name" ]] && { print -r -- "Name of the atom-string parameter needed as first argument, see -h/--help"; return 3; }
+[[ -z "$name" ]] && { print -r -- "Name of the atom-parameter to create is needed, see -h/--help"; return 3; }
 
 local next_read3_var_name="${ZREDIS_CMD[queue_${name}_val_next_read_prefix]}${name}"
 local idx="${(P)next_read3_var_name:-1}"
@@ -47,7 +47,7 @@ while (( 1 )); do
         (( ++ idx ))
         : ${(P)next_read3_var_name::=$idx}
     else
-        (( error )) || (( read )) || { [[ -z "$OPT_QUIET" ]] && print "atom-me-get: the multi-element queue is empty"; error=10; }
+        (( error )) || (( read )) || { [[ -z "$OPT_QUIET" ]] && print "atom-me-get: the queue is empty"; error=10; }
         break
     fi
 done
