*-me-{push,get}: Default write/read index, detection of unsetup me-queue

diff --git a/atom-me-get b/atom-me-get
--- a/atom-me-get
+++ b/atom-me-get
@@ -9,6 +9,7 @@ typeset -g REPLY=""
 
 # Uneeded, but left for future functionality 
 local tpe="${ZREDIS_CMD[queue_${1}_val_type]}"  # read to have the value handy
+[[ -z "$tpe" ]] && { print -r -- "The ME queue \`$1' isn't setup, see atom-me-setup -h, aborting..."; return 1; }
 [[ "$tpe" = (#i)(hash|zset) ]] && typeset -ga reply
 reply=()
 
@@ -16,7 +17,7 @@ reply=()
 typeset -gA ZREDIS_CMD
 
 zparseopts -E -D -A opthash h -help v -verbose q -quiet a -no-ansi n || \
-          { print -r -- "Improper options given, see help (-h/--help)"; return 1; }
+          { print -r -- "Improper options given, see help (-h/--help)"; return 2; }
 
 (( ${+opthash[-h]} + ${+opthash[--help]} ))     && local OPT_HELP="-h"
 (( ${+opthash[-v]} + ${+opthash[--verbose]} ))  && local OPT_VERBOSE="-v"
@@ -24,10 +25,10 @@ zparseopts -E -D -A opthash h -help v -verbose q -quiet a -no-ansi n || \
 (( ${+opthash[-a]} + ${+opthash[--no-ansi]} ))  && local OPT_NO_ANSI="-a"
 
 local name="$1" value1_var_name flag2_var_name read=0 error=0
-[[ -z "$name" ]] && { print -r -- "Name of the atom-string parameter needed as first argument, see -h/--help"; return 1; }
+[[ -z "$name" ]] && { print -r -- "Name of the atom-string parameter needed as first argument, see -h/--help"; return 3; }
 
 local next_read3_var_name="${ZREDIS_CMD[queue_${name}_val_next_read_prefix]}${name}"
-local idx="${(P)next_read3_var_name}"
+local idx="${(P)next_read3_var_name:-1}"
 
 while (( 1 )); do
     # value1 - the value, flag2 - flag
@@ -46,7 +47,7 @@ while (( 1 )); do
         (( ++ idx ))
         : ${(P)next_read3_var_name::=$idx}
     else
-        (( error )) || (( read )) || { [[ -z "$OPT_QUIET" ]] && print "atom-me-get: the multi-element queue is empty"; error=1; }
+        (( error )) || (( read )) || { [[ -z "$OPT_QUIET" ]] && print "atom-me-get: the multi-element queue is empty"; error=10; }
         break
     fi
 done
